; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env:smoochiee-st7789-240x240]
board = esp32s3box
build_src_filter =${env.build_src_filter} +<../boards/smoochiee-st7789-240x240>
board_build.arduino.memory_type = qio_opi
board_build.partitions = custom_16Mb.csv
build_flags =
	${env.build_flags}
	-Iboards/smoochiee-st7789-240x240
	-Os
	-DCORE_DEBUG_LEVEL=1
	-DIR_TX_PINS='{{"GPIO 5", 5}, {"GPIO 2", 2}, {"GPIO 3", 3}}'
	-DIR_RX_PINS='{{"GPIO 4", 4}, {"GPIO 2", 2}, {"GPIO 1", 1}}'
	-DRF_TX_PINS='{{"GPIO 1", 1}, {"GPIO 2", 2}, {"GPIO 3", 3}}'
	-DRF_RX_PINS='{{"GPIO 1", 1}, {"GPIO 2", 2}, {"GPIO 4", 4}}'
	-D USE_HSPI_PORT=1
	-DDEVICE_NAME='"Smoochiee ST7789"'

lib_deps =
	    ${env.lib_deps}
      lewisxhe/XPowersLib @0.3.0
